schema_version = "1.0.0"

id = "io_scene_mw"
version = "0.8.105"
name = "Morrowind Blender Plugin"
tagline = "Import/Export files for Morrowind"
maintainer = "Greatness7 <greatness7@gmail.com>"
type = "add-on"
website = "https://blender-morrowind.readthedocs.io/en/latest/"
tags = ["Import-Export"]
blender_version_min = "3.6.0"
license = ["SPDX:GPL-2.0-or-later"]
platforms = ["windows-x64", "macos-arm64", "linux-x64"]

[permissions]
files = "Import/export NIF from/to disk"
clipboard = "Copy and paste pose markers"
