name: build-release-archive
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: copy contents
        shell: bash
        run: sudo rsync -r --exclude="*.git*" . io_scene_mw

      - name: build archive
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -r io_scene_mw.zip io_scene_mw

      - name: create release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "[Changelog](https://github.com/Greatness7/io_scene_mw/tags)"
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: upload release asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./io_scene_mw.zip
          asset_name: io_scene_mw.zip
          asset_content_type: application/zip
