name: build-release-archive
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: copy contents
        shell: bash
        run: sudo rsync -r --exclude="*.git*" . io_scene_mw

      - name: build archive
        run: tar -acf io_scene_mw.zip io_scene_mw

      - name: create release
        uses: notlmn/release-with-changelog@v2
        with:
          header: "### Changelog"
          include-hash: true
          include-range: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: io_scene_mw.zip
